### ISSUE TITLE
Putting LeJos API in GitHub

### ISSUE THREAD

**Issue by typhlluxe** [wheat32/Armold#29]
Put the Lejos API in GitHub at all costs.

**Comment by typhlluxe** [comment]
Allocation of packages:

**Shaun:**
- lejos.hardware
- lejos.internal

**Caroline:**
- lejos.hardware.device (ONLY)
- lejos.remote
- lejos.robotics
- lejos.utility

**Comment by typhlluxe** [comment]
Finished

**Comment by wheat32** [comment]
Not completed. All names need the extension `.java` instead of `.class`.

**Comment by wheat32** [comment]
Now completed. All files have the `.java` extension.
